name: Android APK

on:
  push:
    paths:
      - 'android/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle 8.7
        run: |
          curl -sLo /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          sudo mkdir -p /opt/gradle
          sudo unzip -q /tmp/gradle.zip -d /opt/gradle
          echo "/opt/gradle/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Generate Gradle Wrapper
        working-directory: android
        run: gradle wrapper --gradle-version 8.7

      - name: Build debug APK
        working-directory: android
        run: ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
